---
- hosts: webservers
  become: true
  tasks:
   - name: Update apt cache
      apt:
        update_cache: yes
  - name: installing pkg
    apt: 
      name: "httpd"
      state: "present"
  - name: start apache server
    service:
      name: httpd
      state: started
      enabled: true
  - name: deploy static website
    copy:
      src: index.html
      dest: /var/www/html/
...      
 
 
