---
- hosts: webservers
  become: true
  tasks:
   - name: update
      apt: update_cache=yes 
  - name: installing pkg
     apt: name=apache2 state=lates
  - name: start apache server
    services:
      name: apache2
      state: started
      enabled: true
  - name: deploy static website
    copy:
      src: index.html
      dest: /var/www/html/
 ...
 
