---
- hosts: webservers
  become: true
  tasks:
  - name: installing pkg
    apt:
      name : "httpd"
      state : "present"
  - name : start apache server
    services:
      name: httpd
      state: started
      enabled : true
  - name : deploy static website
    copy :
      src : index.html
      dest : /var/www/html/
 ...
 
