---
- hosts: webservers
  become: true
  tasks:
  - name: installing pkg
    apt: 
      name: "apache2"
      update_cache: yes
      state: "present"
  - name: start apache server
    service:
      name: apache2
      state: started
      enabled: true
  - name: deploy static website
    copy:
      src: index.html
      dest: /var/www/html/
...      
 
 
